name: pypi
on:
  push:
    tags: "v*"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: curl -sSL https://install.python-poetry.org | python3 -
        shell: bash
      - run: poetry build
        shell: bash
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
